import type { DashboardManifest } from '../../src/types.js';

export const dashboardManifest: DashboardManifest = {
  title: 'Adaptive Role Dashboard',
  description:
    'A reusable dashboard framework where roles resolve to independently composed views through a shared manifest.',
  roles: {
    admin: {
      id: 'admin',
      label: 'Admin',
      summary: 'Operate the system through controls, policy coverage, and change governance.',
      description:
        'Admin views emphasize operational trust, role coverage, and policy resolution before deeper analysis.',
      accentLabel: 'Control authority',
      capabilities: ['Role mapping', 'Policy checks', 'Shared governance'],
      defaultViewId: 'command',
      theme: {
        accent: '#2563eb',
        accentSoft: 'rgba(37, 99, 235, 0.12)',
        accentStrong: '#1d4ed8',
        signal: '#f97316',
      },
      views: [
        {
          id: 'command',
          label: 'Command',
          title: 'System Command Center',
          summary: 'Global visibility for coverage, guardrails, and active review load.',
          widgets: [
            {
              id: 'adminHero',
              kind: 'hero',
              title: 'Framework in motion',
              description: 'The admin perspective keeps the entire manifest stable as roles evolve.',
              span: 'full',
              eyebrow: 'Role-driven control plane',
              variant: 'command',
              statIds: ['adminCoverage', 'adminReliability', 'adminDrift'],
              highlights: [
                'Role contracts stay versioned and inspectable.',
                'Views remain decoupled from widget implementations.',
                'Shared primitives prevent duplicated dashboard logic.',
              ],
              actionLabels: ['Inspect contracts', 'Review drift', 'Open queue'],
            },
            {
              id: 'adminMetrics',
              kind: 'metric-strip',
              title: 'Operating picture',
              description: 'Four health metrics pulled straight from the data catalog.',
              span: 'full',
              metricIds: ['adminCoverage', 'adminReliability', 'adminDrift', 'adminLatency'],
            },
            {
              id: 'adminTrend',
              kind: 'trend',
              title: 'Operational health trend',
              description: 'Primary line against benchmark across the last twelve cycles.',
              span: 'wide',
              datasetId: 'adminHealth',
              summary: 'The command layer is outperforming the benchmark with steady acceleration.',
            },
            {
              id: 'adminTargets',
              kind: 'bullet-list',
              title: 'Governance targets',
              description: 'Compact target tracking for policy-led work.',
              span: 'balanced',
              datasetId: 'policyTargets',
              summary: 'Bullet charts compress target visibility without sacrificing readability.',
            },
            {
              id: 'adminFeed',
              kind: 'activity-feed',
              title: 'Live exceptions',
              description: 'Recent events routed from the operating layer.',
              span: 'balanced',
              datasetId: 'adminFeed',
              summary: 'Critical governance issues stay separated from informational events.',
            },
            {
              id: 'adminTable',
              kind: 'table',
              title: 'Workspace accountability',
              description: 'Each row describes a unit currently participating in the role system.',
              span: 'wide',
              datasetId: 'teamMatrix',
              summary: 'The table supports generic row data with per-view column definitions.',
              filterKeys: ['workspace', 'owner', 'status'],
              columns: [
                { key: 'workspace', label: 'Workspace' },
                { key: 'owner', label: 'Owner' },
                { key: 'status', label: 'Status' },
                { key: 'coverage', label: 'Coverage', align: 'right', format: 'percent' },
                { key: 'latency', label: 'Latency', align: 'right', format: 'days' },
                { key: 'lastUpdated', label: 'Updated', align: 'right' },
              ],
            },
            {
              id: 'adminManifest',
              kind: 'manifest',
              title: 'Manifest contract',
              description: 'Why the framework extends cleanly.',
              span: 'balanced',
              notes: [
                'Roles define views, not components.',
                'Widgets resolve through a shared registry.',
                'D3 charts stay data-driven and reusable.',
              ],
            },
          ],
        },
        {
          id: 'governance',
          label: 'Governance',
          title: 'Governance Review',
          summary: 'A tighter view around capacity, targets, and review choreography.',
          widgets: [
            {
              id: 'adminSpotlight',
              kind: 'spotlight',
              title: 'What changes when a new role ships',
              description: 'The framework isolates role additions to a small set of contract files.',
              span: 'full',
              items: [
                'Add datasets without touching existing widgets.',
                'Map a role to purpose-built views.',
                'Reuse the same chart and table primitives.',
              ],
              callsToAction: ['Draft a new role', 'Validate a view', 'Compare contracts'],
            },
            {
              id: 'adminComparison',
              kind: 'comparison',
              title: 'Capacity distribution',
              description: 'Horizontal bars clarify where operational effort is concentrated.',
              span: 'wide',
              datasetId: 'capacityMix',
              summary: 'Bars keep cross-category comparison precise and keyboard-friendly.',
            },
            {
              id: 'adminGovernanceTargets',
              kind: 'bullet-list',
              title: 'Target scorecard',
              description: 'Space-efficient performance versus target.',
              span: 'balanced',
              datasetId: 'policyTargets',
              summary: 'Use bullet charts when space is limited but targets still matter.',
            },
            {
              id: 'adminGovernanceTable',
              kind: 'table',
              title: 'Review ledger',
              description: 'The same table component serves a governance-heavy view.',
              span: 'wide',
              datasetId: 'teamMatrix',
              summary: 'View-level columns let each role emphasize different fields.',
              filterKeys: ['workspace', 'owner', 'status'],
              columns: [
                { key: 'workspace', label: 'Workspace' },
                { key: 'status', label: 'State' },
                { key: 'coverage', label: 'Coverage', align: 'right', format: 'percent' },
                { key: 'latency', label: 'Cycle', align: 'right', format: 'days' },
                { key: 'lastUpdated', label: 'Updated', align: 'right' },
              ],
            },
            {
              id: 'adminGovernanceFeed',
              kind: 'activity-feed',
              title: 'Review stream',
              description: 'Fast read for teams handling changes.',
              span: 'balanced',
              datasetId: 'adminFeed',
              summary: 'Feeds stay generic enough to power any role-specific view.',
            },
          ],
        },
      ],
    },
    analyst: {
      id: 'analyst',
      label: 'Analyst',
      summary: 'Explore signals, compare segments, and convert movement into reusable insights.',
      description:
        'Analyst views are intentionally chart-forward and tuned for discovery instead of governance.',
      accentLabel: 'Signal clarity',
      capabilities: ['Trend exploration', 'Segment comparison', 'Template reuse'],
      defaultViewId: 'signal-desk',
      theme: {
        accent: '#0f766e',
        accentSoft: 'rgba(15, 118, 110, 0.12)',
        accentStrong: '#115e59',
        signal: '#f59e0b',
      },
      views: [
        {
          id: 'signal-desk',
          label: 'Signal Desk',
          title: 'Signal Desk',
          summary: 'A discovery surface optimized for trends, anomalies, and quick comparison.',
          widgets: [
            {
              id: 'analystHero',
              kind: 'hero',
              title: 'Signals worth action',
              description: 'Analyst mode favors patterns and confidence over operational overhead.',
              span: 'full',
              eyebrow: 'Pattern-focused workspace',
              variant: 'analysis',
              statIds: ['analystConfidence', 'analystDrift', 'analystYield'],
              highlights: [
                'Trend and benchmark stay visible together.',
                'Segment comparison is tuned for precise reading.',
                'The same registry powers exploration and review.',
              ],
              actionLabels: ['Inspect outliers', 'Save insight', 'Share snapshot'],
            },
            {
              id: 'analystMetrics',
              kind: 'metric-strip',
              title: 'Signal baseline',
              description: 'Core quality indicators for the analysis workflow.',
              span: 'full',
              metricIds: ['analystConfidence', 'analystDrift', 'analystCycle', 'analystYield'],
            },
            {
              id: 'analystTrend',
              kind: 'trend',
              title: 'Signal quality over time',
              description: 'Primary, benchmark, and optional secondary line in one chart.',
              span: 'wide',
              datasetId: 'analystSignals',
              summary: 'Line charts remain the clearest pattern for time-based confidence change.',
            },
            {
              id: 'analystComparison',
              kind: 'comparison',
              title: 'Segment lift comparison',
              description: 'Ranking-style comparison with targets.',
              span: 'balanced',
              datasetId: 'channelLift',
              summary: 'Horizontal bars make mixed label lengths easy to scan on smaller widths.',
            },
            {
              id: 'analystFeed',
              kind: 'activity-feed',
              title: 'Anomaly queue',
              description: 'Events that should influence the next analytical pass.',
              span: 'balanced',
              datasetId: 'analystFeed',
              summary: 'The feed component gives narrative context beside charts.',
            },
            {
              id: 'analystTable',
              kind: 'table',
              title: 'Segment roster',
              description: 'Structured evidence behind the visual summaries.',
              span: 'wide',
              datasetId: 'modelSegments',
              summary: 'Role-specific views can keep the same dataset while swapping emphasis.',
              filterKeys: ['segment', 'owner', 'state'],
              columns: [
                { key: 'segment', label: 'Segment' },
                { key: 'owner', label: 'Owner' },
                { key: 'state', label: 'State' },
                { key: 'confidence', label: 'Confidence', align: 'right', format: 'percent' },
                { key: 'momentum', label: 'Momentum', align: 'right', format: 'number' },
                { key: 'lastUpdated', label: 'Updated', align: 'right' },
              ],
            },
            {
              id: 'analystManifest',
              kind: 'manifest',
              title: 'Exploration contract',
              description: 'How this view remains a pure manifest concern.',
              span: 'balanced',
              notes: [
                'The line chart does not know about analyst-specific business logic.',
                'Filters are deferred to keep the table responsive.',
                'New roles can opt into the same comparison component.',
              ],
            },
          ],
        },
        {
          id: 'exploration',
          label: 'Exploration',
          title: 'Exploration Board',
          summary: 'Use the same framework for open-ended comparison and experiment follow-up.',
          widgets: [
            {
              id: 'analystSpotlight',
              kind: 'spotlight',
              title: 'Exploration prompts',
              description: 'This role can swap dense monitoring for guided analytical tasks.',
              span: 'full',
              items: [
                'Compare underperforming segments against the benchmark.',
                'Trace recurring false positives to shared attributes.',
                'Promote repeatable insights into dashboard templates.',
              ],
              callsToAction: ['Create watchlist', 'Export comparison', 'Open notebook'],
            },
            {
              id: 'analystExplorationComparison',
              kind: 'comparison',
              title: 'Cross-segment pressure',
              description: 'Same dataset, different framing.',
              span: 'wide',
              datasetId: 'channelLift',
              summary: 'The comparison component adapts to another view with no rendering changes.',
            },
            {
              id: 'analystTargets',
              kind: 'bullet-list',
              title: 'Quality targets',
              description: 'Where the analysis practice needs reinforcing.',
              span: 'balanced',
              datasetId: 'anomalyTargets',
              summary: 'Bullet charts keep multiple precision targets compact.',
            },
            {
              id: 'analystExplorationTable',
              kind: 'table',
              title: 'Reusable segments',
              description: 'A deeper table view for exploration sessions.',
              span: 'wide',
              datasetId: 'modelSegments',
              summary: 'Tables remain a durable fallback for exact values and keyboard access.',
              filterKeys: ['segment', 'owner', 'state'],
              columns: [
                { key: 'segment', label: 'Segment' },
                { key: 'confidence', label: 'Confidence', align: 'right', format: 'percent' },
                { key: 'momentum', label: 'Momentum', align: 'right', format: 'number' },
                { key: 'state', label: 'Status' },
                { key: 'lastUpdated', label: 'Updated', align: 'right' },
              ],
            },
            {
              id: 'analystExplorationFeed',
              kind: 'activity-feed',
              title: 'Exploration notes',
              description: 'Recent actions connected to the discovery cycle.',
              span: 'balanced',
              datasetId: 'analystFeed',
              summary: 'Narrative cards complement more exploratory use cases.',
            },
          ],
        },
      ],
    },
    business: {
      id: 'business',
      label: 'Business User',
      summary: 'Turn complex system data into portfolio-ready planning and prioritization.',
      description:
        'Business views are designed for narrative clarity, coverage, and decision support.',
      accentLabel: 'Portfolio confidence',
      capabilities: ['Portfolio tracking', 'Planning clarity', 'Decision pacing'],
      defaultViewId: 'portfolio',
      theme: {
        accent: '#ea580c',
        accentSoft: 'rgba(234, 88, 12, 0.12)',
        accentStrong: '#c2410c',
        signal: '#2563eb',
      },
      views: [
        {
          id: 'portfolio',
          label: 'Portfolio',
          title: 'Portfolio Narrative',
          summary: 'A calmer view for leadership readouts, coverage, and directional confidence.',
          widgets: [
            {
              id: 'businessHero',
              kind: 'hero',
              title: 'A narrative dashboard, not a data dump',
              description: 'This role remixes the same framework into a planning-oriented reading experience.',
              span: 'full',
              eyebrow: 'Decision-ready perspective',
              variant: 'portfolio',
              statIds: ['businessCoverage', 'businessVelocity', 'businessRisk'],
              highlights: [
                'Priority coverage stays visible before detail.',
                'Confidence is paired with plain-language context.',
                'The framework supports executive and operator roles together.',
              ],
              actionLabels: ['Review priorities', 'Align planning', 'Share outlook'],
            },
            {
              id: 'businessMetrics',
              kind: 'metric-strip',
              title: 'Portfolio signals',
              description: 'A concise readout for decision makers.',
              span: 'full',
              metricIds: ['businessCoverage', 'businessVelocity', 'businessRisk', 'businessCycle'],
            },
            {
              id: 'businessTrend',
              kind: 'trend',
              title: 'Forecast confidence',
              description: 'Time-based visibility into how the portfolio is moving.',
              span: 'wide',
              datasetId: 'businessForecast',
              summary: 'A line chart keeps the long-term shape readable for non-specialists.',
            },
            {
              id: 'businessComparison',
              kind: 'comparison',
              title: 'Portfolio contribution',
              description: 'Which initiative clusters are carrying the strongest signal.',
              span: 'balanced',
              datasetId: 'portfolioValue',
              summary: 'Comparisons help business roles decide where attention is most valuable.',
            },
            {
              id: 'businessTargets',
              kind: 'bullet-list',
              title: 'Execution targets',
              description: 'Compact goals for portfolio-level planning.',
              span: 'balanced',
              datasetId: 'growthTargets',
              summary: 'The same D3 primitive can support planning language just as well as operations.',
            },
            {
              id: 'businessFeed',
              kind: 'activity-feed',
              title: 'Planning stream',
              description: 'Recent events reworded into narrative-friendly context.',
              span: 'balanced',
              datasetId: 'businessFeed',
              summary: 'This role trades dense operational noise for focused updates.',
            },
            {
              id: 'businessTable',
              kind: 'table',
              title: 'Initiative ledger',
              description: 'Exact values remain available alongside the narrative layer.',
              span: 'wide',
              datasetId: 'initiativeLedger',
              summary: 'Tables keep the framework extensible to audit, export, and downstream workflows.',
              filterKeys: ['initiative', 'owner', 'state'],
              columns: [
                { key: 'initiative', label: 'Initiative' },
                { key: 'owner', label: 'Owner' },
                { key: 'state', label: 'State' },
                { key: 'confidence', label: 'Confidence', align: 'right', format: 'percent' },
                { key: 'velocity', label: 'Velocity', align: 'right', format: 'number' },
                { key: 'lastUpdated', label: 'Updated', align: 'right' },
              ],
            },
          ],
        },
        {
          id: 'planning',
          label: 'Planning',
          title: 'Planning Review',
          summary: 'A simpler decision board for prioritization and next-step alignment.',
          widgets: [
            {
              id: 'businessSpotlight',
              kind: 'spotlight',
              title: 'Planning choreography',
              description: 'This role can choose a more narrative-led composition without new code paths.',
              span: 'full',
              items: [
                'Pull priority data from the shared catalog.',
                'Expose only the charts needed for decision making.',
                'Keep exact values reachable through the same table contract.',
              ],
              callsToAction: ['Adjust targets', 'Open risks', 'Publish summary'],
            },
            {
              id: 'businessPlanningComparison',
              kind: 'comparison',
              title: 'Attention allocation',
              description: 'Which initiative lanes deserve the next planning pass.',
              span: 'wide',
              datasetId: 'portfolioValue',
              summary: 'The comparison card stays valid across strategy and execution modes.',
            },
            {
              id: 'businessPlanningTargets',
              kind: 'bullet-list',
              title: 'Planning targets',
              description: 'Compact thresholds for confidence and pace.',
              span: 'balanced',
              datasetId: 'growthTargets',
              summary: 'The business role keeps targets visible without heavy visual density.',
            },
            {
              id: 'businessPlanningTable',
              kind: 'table',
              title: 'Planning ledger',
              description: 'Exact values for the next portfolio pass.',
              span: 'wide',
              datasetId: 'initiativeLedger',
              summary: 'The table is still view-configured, not component-hardcoded.',
              filterKeys: ['initiative', 'owner', 'state'],
              columns: [
                { key: 'initiative', label: 'Initiative' },
                { key: 'confidence', label: 'Confidence', align: 'right', format: 'percent' },
                { key: 'velocity', label: 'Velocity', align: 'right', format: 'number' },
                { key: 'state', label: 'State' },
                { key: 'lastUpdated', label: 'Updated', align: 'right' },
              ],
            },
            {
              id: 'businessPlanningManifest',
              kind: 'manifest',
              title: 'Framework notes',
              description: 'Extensibility reminders for future scenarios.',
              span: 'balanced',
              notes: [
                'One role can expose multiple experience tiers.',
                'Narrative and analytical views can share the same data layer.',
                'Role additions stay config-first instead of component-first.',
              ],
            },
          ],
        },
      ],
    },
  },
};
