import type { DataCatalog } from '../../src/types.js';

export const demoData: DataCatalog = {
  metrics: {
    adminCoverage: {
      id: 'adminCoverage',
      label: 'Workspace coverage',
      value: 92,
      delta: 4.5,
      trend: 'up',
      unit: 'percent',
      context: 'Role policies mapped across active views.',
      sparkline: [64, 68, 70, 73, 76, 80, 84, 87, 90, 92],
    },
    adminReliability: {
      id: 'adminReliability',
      label: 'Service reliability',
      value: 99.94,
      delta: 0.12,
      trend: 'up',
      unit: 'percent',
      context: 'Stable delivery across dashboard contracts.',
      sparkline: [99.2, 99.4, 99.6, 99.7, 99.75, 99.81, 99.86, 99.9, 99.92, 99.94],
    },
    adminDrift: {
      id: 'adminDrift',
      label: 'Policy drift',
      value: 7,
      delta: -3,
      trend: 'down',
      unit: 'number',
      context: 'Configs requiring review after recent changes.',
      sparkline: [18, 16, 14, 13, 12, 11, 10, 9, 8, 7],
    },
    adminLatency: {
      id: 'adminLatency',
      label: 'Decision latency',
      value: 2.4,
      delta: -0.7,
      trend: 'down',
      unit: 'days',
      context: 'Average turnaround for workspace approvals.',
      sparkline: [4.8, 4.6, 4.2, 4.1, 3.7, 3.3, 3.1, 2.9, 2.6, 2.4],
    },
    analystConfidence: {
      id: 'analystConfidence',
      label: 'Signal confidence',
      value: 87,
      delta: 6.2,
      trend: 'up',
      unit: 'percent',
      context: 'Model-backed confidence for surfaced insights.',
      sparkline: [60, 63, 67, 68, 72, 75, 79, 82, 85, 87],
    },
    analystDrift: {
      id: 'analystDrift',
      label: 'Anomaly drift',
      value: 12,
      delta: -4,
      trend: 'down',
      unit: 'percent',
      context: 'Unexpected pattern movement against baseline.',
      sparkline: [28, 25, 24, 22, 21, 18, 17, 15, 13, 12],
    },
    analystCycle: {
      id: 'analystCycle',
      label: 'Insight cycle',
      value: 1.6,
      delta: -0.3,
      trend: 'down',
      unit: 'days',
      context: 'Average time to move from signal to review.',
      sparkline: [3.1, 2.8, 2.6, 2.5, 2.3, 2.2, 2.0, 1.9, 1.8, 1.6],
    },
    analystYield: {
      id: 'analystYield',
      label: 'Experiment yield',
      value: 31,
      delta: 8,
      trend: 'up',
      unit: 'percent',
      context: 'Hypotheses that turned into retained actions.',
      sparkline: [11, 13, 14, 18, 19, 21, 24, 27, 29, 31],
    },
    businessCoverage: {
      id: 'businessCoverage',
      label: 'Goal coverage',
      value: 84,
      delta: 5.4,
      trend: 'up',
      unit: 'percent',
      context: 'Share of priorities with active dashboard tracking.',
      sparkline: [52, 56, 58, 61, 66, 70, 73, 76, 80, 84],
    },
    businessVelocity: {
      id: 'businessVelocity',
      label: 'Initiative velocity',
      value: 18,
      delta: 3,
      trend: 'up',
      unit: 'number',
      context: 'Workstreams moving inside the expected range.',
      sparkline: [8, 9, 10, 11, 12, 13, 14, 16, 17, 18],
    },
    businessRisk: {
      id: 'businessRisk',
      label: 'At-risk bets',
      value: 6,
      delta: -2,
      trend: 'down',
      unit: 'number',
      context: 'Portfolio items below confidence threshold.',
      sparkline: [12, 11, 10, 10, 9, 8, 8, 7, 7, 6],
    },
    businessCycle: {
      id: 'businessCycle',
      label: 'Planning cycle',
      value: 12,
      delta: -1.8,
      trend: 'down',
      unit: 'days',
      context: 'Time to align planning changes across teams.',
      sparkline: [18, 17, 16, 16, 15, 15, 14, 13, 13, 12],
    },
  },
  trends: {
    adminHealth: [
      { label: 'Jan', primary: 72, benchmark: 68 },
      { label: 'Feb', primary: 74, benchmark: 69 },
      { label: 'Mar', primary: 76, benchmark: 71 },
      { label: 'Apr', primary: 79, benchmark: 72 },
      { label: 'May', primary: 82, benchmark: 74 },
      { label: 'Jun', primary: 81, benchmark: 75 },
      { label: 'Jul', primary: 84, benchmark: 77 },
      { label: 'Aug', primary: 86, benchmark: 78 },
      { label: 'Sep', primary: 88, benchmark: 80 },
      { label: 'Oct', primary: 90, benchmark: 82 },
      { label: 'Nov', primary: 92, benchmark: 83 },
      { label: 'Dec', primary: 94, benchmark: 85 },
    ],
    analystSignals: [
      { label: 'Jan', primary: 42, benchmark: 38, secondary: 28 },
      { label: 'Feb', primary: 48, benchmark: 40, secondary: 30 },
      { label: 'Mar', primary: 55, benchmark: 44, secondary: 34 },
      { label: 'Apr', primary: 58, benchmark: 46, secondary: 37 },
      { label: 'May', primary: 61, benchmark: 48, secondary: 39 },
      { label: 'Jun', primary: 68, benchmark: 51, secondary: 43 },
      { label: 'Jul', primary: 72, benchmark: 54, secondary: 46 },
      { label: 'Aug', primary: 75, benchmark: 57, secondary: 49 },
      { label: 'Sep', primary: 79, benchmark: 59, secondary: 51 },
      { label: 'Oct', primary: 82, benchmark: 61, secondary: 53 },
      { label: 'Nov', primary: 84, benchmark: 63, secondary: 56 },
      { label: 'Dec', primary: 88, benchmark: 66, secondary: 59 },
    ],
    businessForecast: [
      { label: 'Jan', primary: 54, benchmark: 50 },
      { label: 'Feb', primary: 57, benchmark: 51 },
      { label: 'Mar', primary: 59, benchmark: 53 },
      { label: 'Apr', primary: 62, benchmark: 54 },
      { label: 'May', primary: 64, benchmark: 56 },
      { label: 'Jun', primary: 67, benchmark: 58 },
      { label: 'Jul', primary: 69, benchmark: 60 },
      { label: 'Aug', primary: 73, benchmark: 61 },
      { label: 'Sep', primary: 76, benchmark: 63 },
      { label: 'Oct', primary: 79, benchmark: 65 },
      { label: 'Nov', primary: 81, benchmark: 66 },
      { label: 'Dec', primary: 84, benchmark: 68 },
    ],
  },
  comparisons: {
    capacityMix: [
      { label: 'Access', value: 88, target: 92, note: 'Requests landing cleanly.' },
      { label: 'Quality', value: 81, target: 84, note: 'Template coverage improving.' },
      { label: 'Observability', value: 74, target: 80, note: 'More rule visibility needed.' },
      { label: 'Change review', value: 69, target: 76, note: 'Approval queue still uneven.' },
    ],
    channelLift: [
      { label: 'Search', value: 78, target: 72, note: 'Strongest sustained movement.' },
      { label: 'Lifecycle', value: 67, target: 65, note: 'Quality stable, volume rising.' },
      { label: 'Partner', value: 53, target: 58, note: 'Needs tighter segmentation.' },
      { label: 'Direct', value: 61, target: 60, note: 'Moderate gains, low variance.' },
    ],
    portfolioValue: [
      { label: 'Expansion', value: 86, target: 80, note: 'Clear top performer.' },
      { label: 'Retention', value: 71, target: 74, note: 'Confidence rebounding.' },
      { label: 'Efficiency', value: 63, target: 68, note: 'Execution depth is uneven.' },
      { label: 'New bets', value: 58, target: 62, note: 'Needs sharper gating.' },
    ],
  },
  bulletSets: {
    policyTargets: [
      { label: 'Role contracts', value: 92, target: 95, floor: 70, stretch: 100, unit: '%', note: 'Coverage of manifest validation.' },
      { label: 'Review SLA', value: 83, target: 90, floor: 60, stretch: 100, unit: '%', note: 'Change routing inside threshold.' },
      { label: 'Risk resolution', value: 76, target: 82, floor: 55, stretch: 100, unit: '%', note: 'Critical issues closed within window.' },
    ],
    anomalyTargets: [
      { label: 'Pattern clarity', value: 79, target: 84, floor: 50, stretch: 100, unit: '%', note: 'High-signal explanation rate.' },
      { label: 'Alert precision', value: 73, target: 80, floor: 50, stretch: 100, unit: '%', note: 'False positives trending down.' },
      { label: 'Experiment reuse', value: 68, target: 75, floor: 45, stretch: 100, unit: '%', note: 'Templates reused across questions.' },
    ],
    growthTargets: [
      { label: 'Priority coverage', value: 84, target: 88, floor: 55, stretch: 100, unit: '%', note: 'Tracked work against roadmap.' },
      { label: 'Execution pace', value: 72, target: 78, floor: 45, stretch: 100, unit: '%', note: 'Initiatives closing on time.' },
      { label: 'Confidence index', value: 76, target: 81, floor: 50, stretch: 100, unit: '%', note: 'Leadership-ready summary quality.' },
    ],
  },
  feeds: {
    adminFeed: [
      { id: 'a1', title: 'Template contract updated', detail: 'Overview cards inherited the new access policy labels.', category: 'Config', severity: 'info', time: '08:35' },
      { id: 'a2', title: 'Exception queue exceeded threshold', detail: 'Seven workspaces need manual review after scope changes.', category: 'Governance', severity: 'attention', time: '09:10' },
      { id: 'a3', title: 'Fallback renderer recovered', detail: 'The shared widget registry handled a missing optional field without breaking view resolution.', category: 'Runtime', severity: 'info', time: '10:05' },
      { id: 'a4', title: 'Critical role mismatch prevented', detail: 'A stale admin view token was blocked before publish.', category: 'Policy', severity: 'critical', time: '11:18' },
    ],
    analystFeed: [
      { id: 'n1', title: 'Signal confidence crossed guardrail', detail: 'Forecast confidence is above the reuse threshold for two consecutive cycles.', category: 'Signal', severity: 'info', time: '08:42' },
      { id: 'n2', title: 'Partner segment flagged', detail: 'Observed lift fell below the expected range after the latest split.', category: 'Variance', severity: 'attention', time: '09:26' },
      { id: 'n3', title: 'Reusable insight saved', detail: 'A new comparison template was published for future dashboards.', category: 'Library', severity: 'info', time: '10:31' },
      { id: 'n4', title: 'Benchmark drift detected', detail: 'Reference line moved faster than the model expected over the last 14 days.', category: 'Model', severity: 'critical', time: '12:04' },
    ],
    businessFeed: [
      { id: 'b1', title: 'Portfolio review ready', detail: 'Three initiatives now have narrative summaries and refreshed targets.', category: 'Planning', severity: 'info', time: '08:18' },
      { id: 'b2', title: 'New bet added to watchlist', detail: 'The latest initiative lacks confidence coverage and needs closer inspection.', category: 'Portfolio', severity: 'attention', time: '09:54' },
      { id: 'b3', title: 'Execution pace improved', detail: 'Delivery moved above the trailing six-week average.', category: 'Delivery', severity: 'info', time: '11:02' },
      { id: 'b4', title: 'Scenario confidence dropped', detail: 'One planning stream is now outside the preferred risk range.', category: 'Scenario', severity: 'critical', time: '12:11' },
    ],
  },
  tables: {
    teamMatrix: [
      { id: 't1', workspace: 'Core Platform', owner: 'Operations', status: 'Aligned', coverage: 97, latency: 1.2, lastUpdated: '2h ago' },
      { id: 't2', workspace: 'Growth Ops', owner: 'Revenue', status: 'Review', coverage: 83, latency: 2.8, lastUpdated: '45m ago' },
      { id: 't3', workspace: 'Support Enablement', owner: 'Care', status: 'Aligned', coverage: 91, latency: 1.6, lastUpdated: '1h ago' },
      { id: 't4', workspace: 'Finance Signals', owner: 'Finance', status: 'Risk', coverage: 76, latency: 3.9, lastUpdated: '12m ago' },
    ],
    modelSegments: [
      { id: 'm1', segment: 'Lifecycle Cohort', owner: 'Insights', confidence: 88, momentum: 18, state: 'Healthy', lastUpdated: '3h ago' },
      { id: 'm2', segment: 'Self-Serve', owner: 'Analytics', confidence: 74, momentum: 7, state: 'Watch', lastUpdated: '55m ago' },
      { id: 'm3', segment: 'Enterprise Motion', owner: 'Strategy', confidence: 81, momentum: 12, state: 'Healthy', lastUpdated: '1h ago' },
      { id: 'm4', segment: 'Partner Motion', owner: 'Research', confidence: 63, momentum: -4, state: 'Investigate', lastUpdated: '14m ago' },
    ],
    initiativeLedger: [
      { id: 'i1', initiative: 'Platform Renewal', owner: 'Portfolio Office', confidence: 84, velocity: 19, state: 'On track', lastUpdated: '4h ago' },
      { id: 'i2', initiative: 'Workflow Reset', owner: 'Operations', confidence: 71, velocity: 14, state: 'Watch', lastUpdated: '38m ago' },
      { id: 'i3', initiative: 'Expansion Pack', owner: 'Growth', confidence: 89, velocity: 21, state: 'On track', lastUpdated: '2h ago' },
      { id: 'i4', initiative: 'New Horizon', owner: 'Strategy', confidence: 58, velocity: 9, state: 'Risk', lastUpdated: '21m ago' },
    ],
  },
};
